CUDA_VISIBLE_DEVICES=0 python examples/fastspeech2_libritts/train_fastspeech2.py \
  --train-dir ./libtitts/train/ \
  --dev-dir ./libtitts/valid/ \
  --outdir ./examples/fastspeech2_libritts/outdir_libri/ \
  --config ./examples/fastspeech2_libritts/conf/fastspeech2libritts.yaml \
  --use-norm 1 \
  --f0-stat ./libtitts/stats_f0.npy \
  --energy-stat ./libtitts/stats_energy.npy \
  --mixed_precision 1 \
  --dataset_config preprocess/libritts_preprocess.yaml \
  --dataset_stats ./libtitts/stats.npy